use crate::config::model::RulesConfig;
use crate::config::pattern::GlobPattern;
use crate::model::EntryType;

/// Result of attribute classification.
#[derive(Debug, Clone)]
pub struct Attributes {
    pub generated: bool,
    pub sensitive: bool,
    pub text: Option<bool>,
    pub binary: Option<bool>,
    pub reason_codes: Vec<String>,
}

/// Known generated file/directory name patterns.
fn known_generated_names() -> Vec<&'static str> {
    vec![
        "Cargo.lock",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "go.sum",
        "Gemfile.lock",
    ]
}

/// Known generated directory names.
fn known_generated_dirs() -> Vec<&'static str> {
    vec!["target", "dist", "build", "out", ".next", ".nuxt"]
}

/// Known sensitive file patterns.
fn known_sensitive_names() -> Vec<&'static str> {
    vec![
        ".env",
        ".env.local",
        ".env.production",
        "*.pem",
        "*.key",
        "*.cert",
        "id_rsa",
        "id_ed25519",
        ".credentials",
        ".netrc",
        "credentials.json",
        "service-account.json",
        "*.secret.*",
        ".secret",
    ]
}

/// Known binary extensions.
fn known_binary_extensions() -> Vec<&'static str> {
    vec![
        "png", "jpg", "jpeg", "gif", "bmp", "ico", "svg", "woff", "woff2", "ttf", "eot", "pdf",
        "doc", "docx", "xls", "xlsx", "ppt", "pptx", "zip", "tar", "gz", "bz2", "xz", "7z", "rar",
        "exe", "dll", "so", "dylib", "wasm", "o", "a", "lib", "obj", "pyc", "pyo", "class", "jar",
        "bin", "dat", "db", "sqlite", "mp3", "mp4", "avi", "mov", "mkv",
    ]
}

/// Classify generated, sensitive, text/binary attributes for an entry.
///
/// Does NOT read file content.
pub fn classify_attributes(
    name: &str,
    path: &str,
    entry_type: EntryType,
    rules: &RulesConfig,
) -> Attributes {
    let mut generated = false;
    let mut sensitive = false;
    let mut reason_codes = Vec::new();

    // Check generated by exact name
    if known_generated_names().contains(&name) {
        generated = true;
        reason_codes.push("known_generated_name".into());
    }

    // Check generated by directory name
    if entry_type == EntryType::Directory && known_generated_dirs().contains(&name) {
        generated = true;
        reason_codes.push("known_generated_directory".into());
    }

    // Check generated by user-generated patterns (like lockfile in spec)
    // Note: lockfile is special - it's generated=true but not ignore

    // Check sensitive by exact name
    for pattern in known_sensitive_names() {
        if let Some(p) = GlobPattern::compile(pattern)
            && (p.matches(path) || p.matches(name))
        {
            sensitive = true;
            reason_codes.push("sensitive_name_pattern".into());
            break;
        }
    }

    // Check sensitive by user patterns
    for pattern in &rules.sensitive_patterns {
        if let Some(p) = GlobPattern::compile(pattern)
            && p.matches(path)
        {
            sensitive = true;
            reason_codes.push("matched_sensitive_pattern".into());
            break;
        }
    }

    // Binary/text detection by extension
    let (binary, text) = detect_binary(name);

    Attributes {
        generated,
        sensitive,
        text,
        binary,
        reason_codes,
    }
}

fn detect_binary(name: &str) -> (Option<bool>, Option<bool>) {
    if let Some(dot) = name.rfind('.') {
        let ext = name[dot + 1..].to_lowercase();
        if known_binary_extensions().contains(&ext.as_str()) {
            return (Some(true), Some(false));
        }
    }
    (Some(false), Some(true))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::model::RulesConfig;

    fn empty_rules() -> RulesConfig {
        RulesConfig {
            priority_overrides: vec![],
            role_overrides: vec![],
            ignore_patterns: vec![],
            sensitive_patterns: vec![],
        }
    }

    #[test]
    fn test_env_is_sensitive() {
        let attrs = classify_attributes(".env", ".env", EntryType::File, &empty_rules());
        assert!(attrs.sensitive);
        assert!(!attrs.generated);
    }

    #[test]
    fn test_generated_lockfile() {
        let attrs =
            classify_attributes("Cargo.lock", "Cargo.lock", EntryType::File, &empty_rules());
        assert!(attrs.generated);
        assert!(!attrs.sensitive);
    }

    #[test]
    fn test_generated_directory() {
        let attrs = classify_attributes("target", "target", EntryType::Directory, &empty_rules());
        assert!(attrs.generated);
    }

    #[test]
    fn test_binary_by_extension() {
        let attrs = classify_attributes("image.png", "image.png", EntryType::File, &empty_rules());
        assert_eq!(attrs.binary, Some(true));
        assert_eq!(attrs.text, Some(false));
    }

    #[test]
    fn test_text_file() {
        let attrs = classify_attributes("main.rs", "main.rs", EntryType::File, &empty_rules());
        assert_eq!(attrs.text, Some(true));
        assert_eq!(attrs.binary, Some(false));
    }

    #[test]
    fn test_user_sensitive_pattern() {
        let mut rules = empty_rules();
        rules.sensitive_patterns.push("*.secret.json".into());
        let attrs = classify_attributes(
            "data.secret.json",
            "data.secret.json",
            EntryType::File,
            &rules,
        );
        assert!(attrs.sensitive);
    }

    #[test]
    fn test_attributes_independent_of_role() {
        let attrs =
            classify_attributes("Cargo.lock", "Cargo.lock", EntryType::File, &empty_rules());
        assert!(attrs.generated); // generated flag is independent
    }
}
